FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY requirements-streamlit.txt /app/requirements-streamlit.txt
RUN pip install --no-cache-dir -r requirements-streamlit.txt

COPY frontend/ /app/frontend/
COPY data/ /app/data/

EXPOSE 8501

CMD ["streamlit", "run", "frontend/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
